name: Upload to S3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl private --follow-symlinks --exclude '.git*/*' --exclude '.gitignore'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'   # optional: defaults to us-east-1
#         DEST_DIR: 'The directory inside of the S3 bucket you wish to sync/upload, default is root (/)'
        SOURCE_DIR: './README.md'      # optional: defaults to entire repository (The local directory (or file) you wish to sync/upload to S3.)
